apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: ui-ger-ui719-pip234-rebel-rat
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-719-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: ui
  namespace: ui-ger-ui719-pip234-rebel-rat
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: ger-ui719-pip234-rebel-rat
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-719-merge-24ab4f08dc6d96bc72410f3f07dc7acb84d3c71c
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: api-ger-ui719-pip234-rebel-rat
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: api
  namespace: api-ger-ui719-pip234-rebel-rat
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 841ebace7622643f34fa1e7ef55464e7cbb4ab8c
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: ger-ui719-pip234-rebel-rat
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-53b7514c036eb3bfed4fdb3b350d3c3b3e957ad9
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: worker-ger-ui719-pip234-rebel-rat
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: worker
  namespace: worker-ger-ui719-pip234-rebel-rat
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: fc236f47f4c511c7629bae0bf69eaa0fe284c274
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: ger-ui719-pip234-rebel-rat
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: pipeline-ger-ui719-pip234-rebel-rat
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-234-merge-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ger-ui719-pip234-rebel-rat
  name: pipeline
  namespace: pipeline-ger-ui719-pip234-rebel-rat
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: refs/pull/234/head
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-234-merge-e528a181ba27c40e7712c1242529afb5272b736f-pipeline-runner
    replicaCount: 0
    sandboxId: ger-ui719-pip234-rebel-rat
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
