apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
  labels:
    sandboxId: default
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 19667d2839f8b5fb091bdbd169113af9ebb4cfa5
  values:
    clusterEnv: staging
    awsAccountId: "242905224710"
    awsRegion: eu-west-1
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-19667d2839f8b5fb091bdbd169113af9ebb4cfa5-pipeline-runner
    sandboxId: default
    memoryRequest: 29Gi
    replicaCount: 1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
